source/accounts/urls.py
from django.urls import path
from .views import login_view, logout_view, register_view, user_activate_view, UserDetailView, \
     UserPasswordChangeView, UserView, update_profile

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('activate/<token>/', user_activate_view, name='user_activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    # path('<int:pk>/update', UserPersonalInfoChangeView.as_view(), name='update'),
    path('<int:pk>/update/', update_profile, name='update'),
    path('<int:pk>/password_change', UserPasswordChangeView.as_view(), name='password_change'),
    path('user/', UserView.as_view(), name='user'),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/v2/', include('api_v2.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import *

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('issue/add/project/<int:pk>/', IssueCreateView.as_view(), name='issue_add'),
    path('issue/<int:pk>/edit/', IssueUpdateView.as_view(), name='update'),
    path('issue/<int:pk>/', IssueView.as_view(), name='issue_view'),
    path('issue/<int:pk>/delete/', IssueDeleteView.as_view(), name='delete'),
    path('status/create/', StatusCreateView.as_view(), name='create_status'),
    path('status/', StatusView.as_view(), name='status_view'),
    path('status/<int:pk>/edit/', StatusUpdateView.as_view(), name='update_status'),
    path('status/<int:pk>/delete/', StatusDeleteView.as_view(), name='delete_status'),
    path('type/create/', TypeCreateView.as_view(), name='type_create'),
    path('type/', TypeView.as_view(), name='type_view'),
    path('type/<int:pk>/edit/', TypeUpdateView.as_view(), name='type_update'),
    path('type/<int:pk>/delete/', TypeDeleteView.as_view(), name='type_delete'),

    path('project/create/', ProjectCreateView.as_view(), name='create_project'),
    path('project/', ProjectView.as_view(), name='view_project'),
    path('project/<int:pk>/edit/', ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:pk>/',  ProjectDetailView.as_view(), name='projects'),
]

source/webapp/views/views_detail.py
from django.http import request
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import TemplateView
from django.views.generic.base import View


class DetailView(TemplateView):
    context_key = 'objects'
    model = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = get_object_or_404(self.model, pk=kwargs['pk'])
        return context


class UpdateView(View):
    form_class = None
    template_name = None
    model = None
    redirect_url = ''
    pk_kwargs = 'pk'
    object_name = None
    item = None

    def get(self, request, **kwargs):
        item = self.get_item()
        form = self.form_class(instance=item)
        return render(request, self.template_name, context={'form': form, self.object_name: item})

    def post(self, request, **kwargs):
        item = self.get_item()
        form = self.form_class(instance=item, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.item = self.get_item()
        form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        return render(self.request, self.template_name, context={'form': form})

    def get_redirect_url(self):
        return self.redirect_url

    def get_item(self):
        pk = self.kwargs.get(self.pk_kwargs)
        item = get_object_or_404(self.model, pk=pk)
        return item

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class DeleteView(View):
    form_class = None
    template_name = None
    model = None
    redirect_url = ''
    pk_kwargs = 'pk'
    object_name = None
    item = None
    page = ''
    key = False

    def get(self, request, *args, **kwargs):
        if self.key == False:
            item = self.get_item()
            form = self.form_class(instance=item)
            return render(request, self.template_name, context={'form': form, self.object_name: item})
        else:
            self.item = self.get_item()
            try:
                self.item.delete()
                return redirect(self.get_redirect_url())
            except Exception:
                return render(request, self.page)

    def post(self, request, *args, **kwargs):
        self.item = self.get_item()
        try:
            self.item.delete()
            return redirect(self.get_redirect_url())
        except:
            return render(request, self.page)

    def get_redirect_url(self):
        return self.redirect_url

    def get_item(self):
        pk = self.kwargs.get(self.pk_kwargs)
        item = get_object_or_404(self.model, pk=pk)
        return item

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class SessionTimeMixin(View):

    time = {}

    def get_session(self):
        urls = self.request.path
        return urls

    def get_login(self):
        self.get_session()

    def static(self):
        pass

    def counter_session(self):
        pass

    def counter_time(self):
        pass

source/webapp/views/views_issue.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from webapp.models import IssueTracker, Project
from webapp.forms import IssueForm, SimpleSearchForm
from django.utils.http import urlencode

from webapp.views.views_detail import SessionTimeMixin


class IndexView(ListView, SessionTimeMixin):
    template_name = 'issue/index.html'
    context_object_name = 'issues'
    model = IssueTracker
    paginate_by = 4
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.get_session()
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(description__icontains=self.search_value) | Q(summary__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class IssueView(DetailView, SessionTimeMixin):
    template_name = 'issue/issue.html'
    context_object_name = 'issue'
    model = IssueTracker

    def get(self, request, *args, **kwargs):
        url = self.get_session()
        print(url)
        return super().get(request, args, kwargs)


class IssueCreateView(LoginRequiredMixin, CreateView):
    template_name = 'issue/create.html'

    model = IssueTracker

    form_class = IssueForm

    # def get_form(self, form_class=None):
    #     form = super().get_form()
    #     form.fields['created_by'].initial = self.request.user
    #     form.fields['project'].initial = self.request.get_project
    #     teams = Team.objects.all()
    #     print(teams)

        # return form

    def form_valid(self, form):
        project = self.get_project()
        self.object = project.issue_project.create(**form.cleaned_data)
        self.object.created_by = self.request.user
        self.object.project = project
        self.object.save()
        return redirect('webapp:index')

    def get_project(self):
        project_pk = self.kwargs.get('pk')
        return get_object_or_404(Project, pk=project_pk)

    def get_form_kwargs(self):
        project_pk = self.kwargs.get('pk')
        project = get_object_or_404(Project, pk=project_pk)
        kwargs = super().get_form_kwargs()
        kwargs['project'] = project
        return kwargs

    def get_success_url(self):
        return reverse('webapp:issue_view', kwargs={'pk': self.object.pk})


class IssueUpdateView(UpdateView, SessionTimeMixin):
    model = IssueTracker
    template_name = 'issue/update.html'
    form_class = IssueForm
    context_object_name = 'issue'

    def get(self, request, *args, **kwargs):
        url = self.get_session()
        print(url)
        return super().get(request, args, kwargs)

    def get_form_kwargs(self):
        project_pk = self.kwargs.get('pk')
        issue = get_object_or_404(IssueTracker, pk=project_pk)
        kwargs = super().get_form_kwargs()
        kwargs['project'] = issue.project
        return kwargs


    def get_success_url(self):
        return reverse('webapp:issue_view', kwargs={'pk': self.object.pk})

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class IssueDeleteView(DeleteView, SessionTimeMixin):
    model = IssueTracker
    template_name = 'issue/delete.html'
    form_class = IssueForm
    context_object_name = 'issue'
    page = 'index'

    def get(self, request, *args, **kwargs):
        url = self.get_session()
        print(url)
        return super().get(request, args, kwargs)

    def get_success_url(self):
        return reverse('webapp:index')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, args, kwargs)

source/webapp/views/views_project.py
from datetime import datetime

from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.http import urlencode
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from accounts.models import Team
from webapp.models import Project
from webapp.forms import ProjectForm, SimpleSearchForm


class ProjectView(ListView):
    template_name = 'project/view_project.html'
    context_object_name = 'projects'
    model = Project
    ordering = ['created_at']
    paginate_by = 3
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name_project__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class ProjectDetailView(DetailView):
    template_name = 'project/projects.html'
    context_object_name = 'project'
    model = Project


class ProjectCreateView(CreateView):
    template_name = 'project/create.html'

    model = Project

    form_class = ProjectForm

    def get_success_url(self):
        return reverse('webapp:view_project')

    def form_valid(self, form):
        team = list(form.cleaned_data.pop("users"))
        team.append(self.request.user)
        self.object = form.save()
        Team.objects.create(user=self.request.user,project=self.object, created_at=datetime.now())
        for user in team:
            Team.objects.create(user=user, project=self.object, created_at=datetime.now())
        return redirect(self.get_success_url())

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class ProjectUpdateView(UpdateView):
    model = Project
    template_name = 'project/update.html'
    form_class = ProjectForm
    context_object_name = 'project'

    def get_success_url(self):
        return reverse('webapp:view_project')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'project/delete.html'
    form_class = ProjectForm
    context_object_name = 'project'
    page = 'error.html'

    def get_success_url(self):
        return reverse('webapp:view_project')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

source/webapp/views/views_status.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from webapp.models import Status
from webapp.forms import StatusForm


class StatusView(ListView):
    template_name = 'status/status_view.html'
    context_object_name = 'statuses'
    model = Status


class StatusCreateView(CreateView):
    template_name = 'status/create_status.html'

    model = Status

    form_class = StatusForm

    def get_success_url(self):
        return reverse('webapp:status_view')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class StatusUpdateView(UpdateView):
    model = Status
    template_name = 'status/update_status.html'
    form_class = StatusForm
    context_object_name = 'status'

    def get_success_url(self):
        return reverse('webapp:status_view')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class StatusDeleteView(DeleteView):
    model = Status
    template_name = 'status/delete_status.html'
    form_class = StatusForm
    context_object_name = 'status'
    page = 'error.html'

    def get_success_url(self):
        return reverse('webapp:status_view')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

source/webapp/views/views_type.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from webapp.models import Type
from webapp.forms import TypeForm


class TypeView(ListView):
    template_name = 'type/type_view.html'
    context_object_name = 'types'
    model = Type


class TypeCreateView(CreateView):
    template_name = 'type/type_create.html'

    model = Type

    form_class = TypeForm

    def get_success_url(self):
        return reverse('webapp:type_view')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class TypeUpdateView(UpdateView):
    model = Type
    template_name = 'type/type_update.html'
    form_class = TypeForm
    context_object_name = 'type'

    def get_success_url(self):
        return reverse('webapp:type_view')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)


class TypeDeleteView(DeleteView):
    model = Type
    template_name = 'type/type_delete.html'
    form_class = TypeForm
    context_object_name = 'type'
    page = 'type_view'

    def get_success_url(self):
        return reverse('webapp:type_view')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        return super().dispatch(request, *args, **kwargs)

source/webapp/templates/issue/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}IssueTracker{% endblock %}</title>
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.11.1/css/all.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <ul class="navbar-nav">
        <li><a class="navbar-brand" href="{% url "webapp:index" %}">На главную</a></li>
        <li><a class="navbar-brand" href="{% url "accounts:user" %}">Пользователи</a></li>

        {% if user.is_authenticated %}
            {% block menu %}{% endblock %}
            <li> <a href="{% url 'accounts:detail' user.pk %}" class="nav-link">Привет ! {{ user.username }} </a></li>
            <a href="{% url 'accounts:logout' %}" class="nav-link">Выход</a>
        {% else %}
            <li><a href="{% url 'accounts:login' %}" class="nav-link">Вход</a></li>
            <li><a href="{% url 'accounts:register' %}" class="nav-link">Sign Up</a></li>
        {% endif %}
    </ul>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>

</html>

source/webapp/templates/issue/create.html
{% extends 'issue/base.html' %}

{% block title %}Create Issue{% endblock %}

{% block content %}
    <h1>Create</h1>
    <form method="POST" action="">
 {% include 'partial/issue_forms.html' with button_text='Create' %}
    </form>
{% endblock %}

source/webapp/templates/issue/delete.html
{% extends "issue/base.html" %}

{% block title %}Delete{% endblock %}

{% block menu %}
{% endblock %}
{% block content %}
    <h1>Are you sure want to delete task "{{ issue }}"?</h1>
    <form method="POST" action="{% url "webapp:delete" issue.pk %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Confirm"></p>
        <p><a href="{% url "webapp:index" %}">Cancel</a></p>
    </form>
{% endblock %}

source/webapp/templates/issue/index.html
{% extends 'issue/base.html' %}

{% block menu %}
    <a class="navbar-brand" href="{% url 'webapp:create_status' %}">Add Statuses</a>
    <a class="navbar-brand" href="{% url 'webapp:status_view' %}">Statuses</a>
     <a class="navbar-brand" href="{% url 'webapp:type_create' %}">Add Type</a>
    <a class="navbar-brand" href="{% url 'webapp:type_view' %}">Types</a>
         <a class="navbar-brand" href="{% url 'webapp:create_project' %}">Add Project</a>
    <a class="navbar-brand" href="{% url 'webapp:view_project' %}">Projects</a>
{% endblock %}
{% block content %}
<h1>IssueTracker:</h1>
<hr/>
    {% include 'partial/simple_search.html' %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% for issue in issues %}
<div class="card">
    <div class="card-body">
    {% if user.is_authenticated %}
         <p style="display:inline "><a href="{% url 'webapp:issue_view' issue.pk %}"><i class="fas fa-book-open"></i></a></p>
        <p style="display:inline "><a href="{% url 'webapp:update' issue.pk %}"><i class="fas fa-file-signature"></i></a></p>
        <p style="display:inline "><a href="{% url 'webapp:delete' issue.pk %}"><i class="fas fa-trash"></i></a></p>
    {%endif%}
        <h5 class="card-title" style="display:inline ">Краткое описание:{{ issue.summary }}</h5>

        <p>Автор : {{ issue.created_by }}</p>
        <p>Проект :{{issue.project }}</p>
        <p class="card-text">Описание : {{ issue.description }}</p>
        <p class="card-text">Статус: {{ issue.status }}</p>
        <p class="card-text">Тип: {{ issue.type }}</p>
        <p class="card-text">Дата : {{ issue.date_ct }}</p>
        {% for issues in project.issue_project.all %}
        <h2>Задачи: {{ issues.summary }}</h2>
    {% endfor %}
    </div>
</div>
<h2></h2>
<hr/>
{% endfor %}
      {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/issue/issue.html
{% extends 'issue/base.html' %}
{% block menu %}
    {% if user.is_authenticated %}
   <li><a class="nav-item nav-link active" href="{% url 'webapp:update' issue.pk %}">Edit</a></li>
   <li><a class="nav-item nav-link active" href="{% url 'webapp:delete' issue.pk %}">Delete</a></li>
    {% endif %}
{% endblock %}
{% block title %}{{ issue.title }}{% endblock %}
{% block content %}
    <h1>Краткое описание:{{issue.summary}}</h1>
    <p>Описание:{{ issue.description}} </p>
    <p>Статус: {{ issue.status}}</p>
    <p>Тип: {{ issue.type}}</p>
{% endblock %}

source/webapp/templates/issue/update.html
{% extends "issue/base.html" %}
{% block menu %}
    <li><a class="navbar-brand"  href="{% url 'webapp:issue_view' issue.pk %}">View</a></li>
{% endblock %}
{% block title %}Update{% endblock %}
{% block content %}
    <h1>Update Issue</h1>
    <form method="POST" action="{% url "webapp:update" issue.pk %}">
        {% csrf_token %}
  {% include 'partial/issue_forms.html' with button_text="Update" %}
    </form>
{% endblock %}

source/webapp/templates/issue/view.html
{% block menu %}
    <li><a class="navbar-brand" href="{% url 'webapp:update' issue.pk %}">Edit</a></li>
{% endblock %}